### ISSUE TITLE
Inline completions indistinguishable from highlighted background

### ISSUE THREAD

**Issue by doraut** [catppuccin/zed#30]
I noticed that inline completions inside highlighted text are indistinguishable from the background:

This is with "Catppuccin Mocha":
![Screenshot from 2024-08-02 09-29-25](https://github.com/user-attachments/assets/1cc89ded-494a-4b7b-80ad-e502d17305b1)

For comparison, this is what it looks like with the "One Dark" Theme:
![image](https://github.com/user-attachments/assets/465b9430-cece-49aa-a86e-9373ed5fdc76)

### Versions
Catppuccin Themes: v0.2.10
Zed: v0.147.1 (Zed Preview)
OS: Linux Wayland ubuntu 22.04

**Comment by tecandrew** [comment]
thanks for reporting. seems like a regression. I remember accommodating for this [in a previous patch](https://github.com/catppuccin/zed/issues/19#issuecomment-2086260867). a regression, or something Linux specific. 

will look into this when I get access to a Linux machine.

i forget if this is something shown by Copilot/Supermaven or Zed's Assistant Panel

**Comment by tecandrew** [comment]
coming back to this to find that my personal Linux PC doesn't play well with Zed since it doesn't have a supported Vulkan GPU. it's unbearably slow.

I'd be happy to merge any fixes on this if one has the time to debug on Linux Desktop

**Comment by ali-42** [comment]
this overrides seems to do the trick for me on catppuccin mocha. I basically just revert back to the previous values for predictives as showed here : https://github.com/catppuccin/zed/pull/20/files

` "experimental.theme_overrides": {
    "predictive": "#7c8ab3",
    "predictive.border": "#babbf1"
  },`

Maybe that is something you can do and see if it breaks anything on mac os (I can't test on mac)

**Comment by tecandrew** [comment]
@ali-42 ahh, thank you for pointing this out. The previous slight blue-tint seems to look fine even on macOS. In a similar manner I'll adjust inlay hints to be a slightly different shade of blue as well.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/1e66271b-06a6-4ce7-9c7a-b102d0a7a2b7">

<img width="725" alt="image" src="https://github.com/user-attachments/assets/70a1eef8-edf4-4102-b334-600147743ad9">

Strange that this bug is only seen on Linux
